TRAIN:
    model: sparse_deit_base_patch16_224
    N: 4
    M: 4
    sparse_optimizer: 1
    layout : NCHW

    workers: 8
    batch_size: 64
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    finetue_lr : 0.01
    lra : 0.01
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.0
    #weight_decay: 0.00005
    #dense weight_decay
    #weight_decay: 0.0001
    weight_decay : 0.000
    sparse_decay : 0.1


    print_freq: 200
    model_dir: deit_base_sparse

    data: /dataset/imagenet




TEST:
    checkpoint_path : deit_small/pretrained_model/